import React, { useEffect, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import { ArrowUpRight, Download, Menu, X, Plus, Minus, Sun, Moon } from "lucide-react";
import { Toaster, toast } from "sonner";
import "./App.css";

const projects = [
  { id: "rebecca", number: "01", title: "A gamified 0→1 platform", quiet: "for a B2C financial product.", kind: "Product design", period: "Oct 2025 — Present", company: "Rebecca Everlene Trust Company", summary: "Leading design from discovery through wireframing, prototyping, and high-fidelity execution for a B2C web platform — restructuring dense content into gamified learning modules and partnering with product and engineering on AI-driven features.", metrics: [["25%", "higher task completion"], ["40%", "lower early drop-off"], ["50%", "faster time-to-prototype"]], tags: ["0→1 product", "Gamified learning", "AI workflows", "B2C"], detail: "A current, confidential product engagement focused on making complex financial learning feel approachable, motivating, and easy to complete." },
  { id: "eyeai", number: "02", title: "Diagnostic workflows", quiet: "and automated reporting for clinicians.", kind: "UX design · Onward Technologies", period: "Jul 2024 — Aug 2024", company: "Onward Technologies — EYE AI", summary: "A regulated B2B health-tech MVP followed end to end: research synthesis, method, and interface. The work turned clinician pain points into a clear, shippable diagnostic workflow.", metrics: [["20%", "faster diagnostic tasks"], ["10→7", "week MVP timeline"], ["5", "severity issues eliminated"]], tags: ["Healthcare", "Research", "Prototyping", "Reporting"], detail: "Applied heuristic evaluation and competitive analysis across 15+ stakeholder workshops, then used journey mapping, iterative prototyping, and early validation to compress the MVP timeline." },
  { id: "optra", number: "03", title: "Zoe, an AI companion", quiet: "inside a health-tech platform.", kind: "Product design · OptraHealth", period: "Dec 2024 — Mar 2025", company: "OptraHealth", summary: "Designed the interaction layer from the ground up alongside mobile onboarding, patient management, and provider monitoring features. Validated across 20+ sessions with patients, parents, and providers.", metrics: [["30%", "higher weekly engagement"], ["28%", "higher tutorial completion"], ["100+", "component library"]], tags: ["AI companion", "Healthcare SaaS", "Design system"], detail: "The product brought patient-facing encouragement and provider-facing oversight into one coherent system, grounded in research and a reusable Figma library." },
  { id: "dab", number: "04", title: "Brand at scale", quiet: "across a client roster.", kind: "Visual design · DAB of India", period: "Jan 2023 — Aug 2023", company: "DAB of India", summary: "Built an AI-assisted design workflow spanning copy, mockups, social and print assets across 25+ clients while maintaining brand standards over 1,000+ assets.", metrics: [["25+", "clients served"], ["1,000+", "assets maintained"], ["5+", "new client wins"]], tags: ["Brand design", "AI-assisted workflow", "Client work"], detail: "A production practice built around consistency: fast exploration, clear brand systems, and pitch decks that helped turn creative work into new relationships." }
];

const skills = [
  ["01", "Product thinking", "Product strategy · Information architecture · Journey mapping · Competitive analysis · A/B testing"],
  ["02", "Research & validation", "User research · Usability testing · Heuristic evaluation · UserTesting · Perplexity · Claude"],
  ["03", "Complex product design", "Design for AI · Design systems · Accessibility (WCAG 2.2) · Regulated healthcare workflows"],
  ["04", "Prototyping & craft", "Figma · Figma Make · Framer · HTML5/CSS · JavaScript · Illustrator · Photoshop · Miro"]
];

const experience = [
  ["UX/UI Designer", "Rebecca Everlene Trust Company", "Oct 2025 — Present", "Leading 0→1 design for a B2C web platform, restructuring dense content into gamified learning modules and integrating AI-automated workflows across 10+ features."],
  ["Product Designer", "OptraHealth", "Dec 2024 — Mar 2025", "Primary designer for Zoe, an AI companion, plus onboarding, patient management, and provider monitoring for a health-tech SaaS platform."],
  ["UX Designer", "Onward Technologies", "Jul 2024 — Aug 2024", "Designed diagnostic workflows and automated reporting for a regulated B2B health-tech MVP, from journey mapping through high-fidelity delivery."],
  ["Visual Designer", "DAB of India", "Jan 2023 — Aug 2023", "Built an AI-assisted design workflow across copy, mockups, and social/print assets for 25+ clients."]
];

function Rail({ index, title, children, testId }) {
  return <div className="rail"><span className="eyebrow">{index} / 04</span><h2 data-testid={`${testId}-heading`}>{title}</h2>{children}</div>;
}

function ProjectCard({ project, onOpen }) {
  return <motion.article className="project-card" data-testid={`project-card-${project.id}`} initial={{ opacity: 0, y: 28 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, amount: .2 }} transition={{ duration: .55 }}>
    <div className="project-top"><span className="project-number">{project.number}</span><span className="eyebrow">{project.kind}</span><span className="project-period">{project.period}</span></div>
    <h3>{project.title}<em>{project.quiet}</em></h3><p className="project-company">{project.company}</p><p className="project-summary">{project.summary}</p>
    <div className="metric-row">{project.metrics.map(([value, label]) => <div key={label} data-testid={`metric-${project.id}-${label}`}><strong>{value}</strong><span>{label}</span></div>)}</div>
    <div className="project-bottom"><div className="tag-row">{project.tags.map(tag => <span className="tag" key={tag}>{tag}</span>)}</div><button className="text-button" data-testid={`case-study-${project.id}-button`} onClick={() => onOpen(project)}>Read case <ArrowUpRight size={15} /></button></div>
  </motion.article>;
}

export default function App() {
  const [theme, setTheme] = useState(() => localStorage.getItem("portfolio-theme") || "dark");
  const [menu, setMenu] = useState(false);
  const [openExp, setOpenExp] = useState(null);
  const [selected, setSelected] = useState(null);
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem("portfolio-theme", theme); }, [theme]);
  const toggleTheme = () => { const next = theme === "dark" ? "light" : "dark"; setTheme(next); toast(`${next === "dark" ? "Carbon" : "Paper"} mode`); };
  const go = (id) => { setMenu(false); document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); };
  return <div className="portfolio-shell"><Toaster position="bottom-right" />
    <header className="site-header" data-testid="portfolio-header"><a className="wordmark" href="#top" data-testid="logo-link">ES<span>/</span> ESHANI SOMWANSHI</a><nav className="desktop-nav" aria-label="Primary navigation">{[["work", "Work"], ["capabilities", "Skills"], ["experience", "Experience"], ["about", "About"]].map(([id, label]) => <a href={`#${id}`} key={id} data-testid={`nav-${id}`}>{label}</a>)}</nav><div className="header-actions"><button className="theme-toggle" onClick={toggleTheme} data-testid="theme-toggle-button" aria-label="Toggle colour theme">{theme === "dark" ? <Sun size={16} /> : <Moon size={16} />}<span>{theme === "dark" ? "Paper" : "Carbon"}</span></button><a href="#contact" className="header-contact" data-testid="header-contact-link">Contact <ArrowUpRight size={15} /></a><button className="menu-button" onClick={() => setMenu(!menu)} data-testid="mobile-menu-button" aria-label="Toggle menu">{menu ? <X /> : <Menu />}</button></div>{menu && <div className="mobile-nav">{[["work", "Work"], ["capabilities", "Skills"], ["experience", "Experience"], ["about", "About"], ["contact", "Contact"]].map(([id, label]) => <button key={id} onClick={() => go(id)} data-testid={`mobile-nav-${id}`}>{label}<ArrowUpRight size={18} /></button>)}</div>}</header>
    <main id="top">
      <section className="hero section-pad"><div className="hero-meta"><span>LOCAL / <b>CHICAGO, IL</b></span><span>PRODUCT / UX DESIGNER</span></div><div className="hero-center"><span className="availability"><i /> AVAILABLE FOR THOUGHTFUL WORK</span><h1>Designing <em>clarity</em><br />into complex<br /><span>systems.</span></h1><p>I work across healthcare, AI, and enterprise products — using research, systems thinking, and visual craft to make complex experiences easier to understand and use.</p><div className="hero-links"><a href="#work" className="button-solid" data-testid="hero-work-button">Selected work <ArrowUpRight size={17} /></a><a href="mailto:eshani.swdesign@gmail.com" className="button-ghost" data-testid="hero-email-button">Start a conversation</a></div></div><div className="hero-footer"><span>SCROLL TO EXPLORE ↓</span><span>© 2026 ESHANI SOMWANSHI</span></div></section>
      <section className="intro-strip"><div className="section-pad strip-grid"><span className="eyebrow">A note on the work</span><p>Good design makes the complicated feel considered. The strongest work here is shown through decisions, outcomes, and the systems behind them — not decorative screenshots.</p><span className="strip-mark">01—04</span></div></section>
      <section className="split-section section-pad" id="work"><Rail index="01" title="Selected work" testId="work"><p>A hierarchy, not a grid. Current product work leads; every other project adds another angle to the same throughline: turning complexity into confidence.</p><div className="rail-note">RESEARCH<br />→ STRUCTURE<br />→ CRAFT</div></Rail><div className="project-list">{projects.map(project => <ProjectCard key={project.id} project={project} onOpen={setSelected} />)}</div></section>
      <section className="split-section dark-band section-pad" id="capabilities"><Rail index="02" title="Capabilities" testId="capabilities"><p>Grouped by what the work needs, not alphabetized into a wall of keywords.</p><div className="rail-note">THE TOOLKIT<br />BEHIND THE WORK</div></Rail><div className="skills-list">{skills.map(([num, title, desc]) => <article className="skill-row" key={title} data-testid={`skill-${num}`}><span className="row-number">{num}</span><h3>{title}</h3><p>{desc}</p><ArrowUpRight size={20} /></article>)}</div></section>
      <section className="split-section section-pad" id="experience"><Rail index="03" title="Experience" testId="experience"><p>Four roles, one throughline: making complex tools feel useful, human, and ready to ship.</p></Rail><div className="experience-list">{experience.map(([role, company, period, summary], idx) => { const isOpen = openExp === idx; return <article className={`experience-row ${isOpen ? "is-open" : ""}`} key={company} data-testid={`experience-${idx}`}><div className="experience-heading"><span className="row-number">0{idx + 1}</span><div><h3>{role}</h3><p>{company}</p></div><span className="period">{period}</span><button onClick={() => setOpenExp(isOpen ? null : idx)} data-testid={`experience-toggle-${idx}`} aria-expanded={isOpen} aria-label={`${isOpen ? "Hide" : "Show"} ${role} details`}>{isOpen ? <Minus /> : <Plus />}</button></div><AnimatePresence>{isOpen && <motion.p className="experience-detail" initial={{ opacity: 0, height: 0 }} animate={{ opacity: 1, height: "auto" }} exit={{ opacity: 0, height: 0 }}>{summary}</motion.p>}</AnimatePresence></article>; })}</div></section>
      <section className="about-section section-pad" id="about"><span className="eyebrow">04 / About</span><div className="about-grid"><h2>Research-led.<br /><em>Systems-minded.</em><br />Always human.</h2><div><p className="about-lede">Eshani Somwanshi is a product and UX designer working at the intersection of research, systems thinking, and visual craft.</p><p className="muted">Her work spans healthcare, AI interaction design, and enterprise workflows — grounded in usability testing, heuristic evaluation, and close collaboration with product and engineering teams.</p><div className="facts"><div><span>EDUCATION</span><b>MS, Human-Computer Interaction<br />DePaul University, 2025</b></div><div><span>BASED IN</span><b>Chicago, Illinois</b></div><div><span>FOCUS</span><b>Healthcare · AI · Enterprise</b></div></div></div></div></section>
      <section className="contact-section section-pad" id="contact"><div className="contact-top"><span className="eyebrow">05 / Get in touch</span><span>OPEN TO GOOD PROBLEMS</span></div><h2>Have a complex<br /><em>product problem?</em></h2><p>I’m interested in thoughtful product work across healthcare, AI, and systems that help people make better decisions.</p><div className="contact-actions"><a href="mailto:eshani.swdesign@gmail.com" className="button-solid" data-testid="contact-email-link">Email Eshani <ArrowUpRight size={17} /></a><a href="https://www.linkedin.com/in/eshani-somwanshi/" target="_blank" rel="noreferrer" className="button-ghost" data-testid="contact-linkedin-link">LinkedIn <ArrowUpRight size={17} /></a></div></section>
    </main><footer className="site-footer section-pad"><span>© 2026 ESHANI SOMWANSHI</span><a href="#top" data-testid="back-to-top-link">BACK TO TOP ↑</a><a href="mailto:eshani.swdesign@gmail.com" data-testid="footer-email-link">eshani.swdesign@gmail.com</a></footer>
    <AnimatePresence>{selected && <motion.div className="modal-backdrop" role="dialog" aria-modal="true" aria-label={`${selected.title} case study`} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} onClick={() => setSelected(null)}><motion.div className="case-modal" initial={{ y: 30 }} animate={{ y: 0 }} exit={{ y: 30 }} onClick={e => e.stopPropagation()}><button className="modal-close" onClick={() => setSelected(null)} data-testid="close-case-study-button" aria-label="Close case study"><X /></button><span className="eyebrow">{selected.number} / {selected.kind}</span><h2>{selected.title}<em>{selected.quiet}</em></h2><p>{selected.detail}</p><div className="metric-row">{selected.metrics.map(([v, l]) => <div key={l}><strong>{v}</strong><span>{l}</span></div>)}</div><button className="button-solid modal-button" onClick={() => setSelected(null)} data-testid="modal-done-button">Close case study <ArrowUpRight size={17} /></button></motion.div></motion.div>}</AnimatePresence>
  </div>;
}